zuul:
  igoredServices: '*'
  routes:
    sample-api:
      path: /sample-api/**
      serviceId: sample-api
      stripPrefix: true

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    non-secure-port: ${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000

ribbon:
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 3
  OkToRetryOnAllOperations: true
  ReadTimeout: 5000
  ConnectTimeout: 1000
  MaxTotalConnections: 300
  MaxConnectionsPerHost: 100
  retryableStatusCodes: 500