server:
  port: 8882

spring:
  application:
    name: gateway-server

  profiles:
    active: local

logging:
  level:
    root: info
    lozm: debug

zuul:
  igoredServices: '*'
  routes:
    sample-api:
      path: /sample-api/**
      serviceId: sample-api
      stripPrefix: true

  ws:
    brokerages:
      chatting-api:
        end-points: /end-points
        brokers:  /topic
        destination-prefixes: /publish
  retryable: true
  ribbon-isolation-strategy: thread
  thread-pool:
    use-separate-thread-pools: true
    thread-pool-key-prefix: gateway-server