server:
  port: 8886

spring:
  application:
    name: community-api

  profiles:
    active: local

logging:
  level:
    root: info
    lozm: debug
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000

ribbon:
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 3
  OkToRetryOnAllOperations: true
  ReadTimeout: 5000
  ConnectTimeout: 1000
  MaxTotalConnections: 300
  MaxConnectionsPerHost: 100
  retryableStatusCodes: 500